-intstyle "ise" -incremental -o "C:/Users/sed/Documents/Frecuencimentro - Presentacion/top_TB_isim_beh.exe" -prj "C:/Users/sed/Documents/Frecuencimentro - Presentacion/top_TB_beh.prj" "work.top_TB" 
